### ISSUE TITLE
improve group name/description

### ISSUE THREAD

**Issue by ownzandy** [hack-duke/hackduke-mentorship-bot#6]
current implementation of the group name is slackid-slackid, which may be confusing for the users
also think about/look into setting a description for each group

**Comment by Briguy52** [comment]
## What we want out of our group name
- Unique (no collisions between groups)
- Easy for mentor to read (can tell who they're helping)
- Easy for participant to read (can tell they're being helped)

## Format

`<ParticipantSlackName> + '-' + <MentorSlackName>`

where both names come from Slack (and are forced to be unique)
- use regex to remove periods and spaces
- user toLowerCase() String prototype method to make everything lowercase for channels

## Challenges

Turns out we can't use periods, spaces, or special characters in the names of channels :(
